# Generated by Django 6.0 on 2025-12-08 21:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('devise', models.CharField(default='EUR', max_length=3)),
                ('tva_default', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('couleur_primaire', models.CharField(default='#1976D2', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Entreprises',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin Entreprise'), ('manager', 'Manager'), ('caissier', 'Caissier'), ('comptable', 'Comptable'), ('lecture_seule', 'Lecture Seule')], default='lecture_seule', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='gestion_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='gestion_user_permissions', to='auth.permission', verbose_name='user permissions')),
                ('entreprise', models.ForeignKey(blank=True, help_text="L'entreprise à laquelle cet utilisateur est rattaché.", null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('justificatif_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('statut_validation', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée')], default='en_attente', max_length=20)),
                ('date_depense', models.DateField()),
                ('declaree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Code-barres ou référence SKU.', max_length=50, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('stock_min_alerte', models.IntegerField(default=5)),
                ('archived', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('total_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Especes'), ('carte', 'Carte'), ('mobile_money', 'Mobile_money')], max_length=20)),
                ('statut', models.CharField(choices=[('payee', 'Payee'), ('annulee', 'Annulee'), ('credit', 'Credit')], default='payee', max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remise_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.article')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='gestion.vente')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['entreprise'], name='gestion_art_entrepr_1d4868_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('entreprise', 'code')},
        ),
    ]
