# Generated by Django 6.0 on 2025-12-08 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('solde_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
            ],
        ),
        migrations.AddField(
            model_name='vente',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.client'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entreprise', 'nom'], name='gestion_cli_entrepr_03c662_idx'),
        ),
    ]
