# Generated by Django 6.0 on 2025-12-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_client_vente_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='sous_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
