# Generated by Django 6.0 on 2025-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_user_email_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='seuil_alerte',
            field=models.IntegerField(default=5),
        ),
    ]
