# Generated by Django 6.0 on 2025-12-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_article_seuil_alerte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depense',
            old_name='description',
            new_name='motif',
        ),
    ]
