# Generated by Django 6.0 on 2025-12-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rename_description_depense_motif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stock_min_alerte',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
