# Generated by Django 6.0 on 2025-12-20 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_remove_article_stock_min_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='nom_client_libre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
