# Generated by Django 6.0 on 2025-12-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_vente_nom_client_libre'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='numero_sequentiel',
            field=models.IntegerField(default=1),
        ),
    ]
