# Generated by Django 6.0 on 2025-12-22 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion', '0009_vente_numero_sequentiel'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='client',
            name='gestion_cli_entrepr_03c662_idx',
        ),
        migrations.RemoveField(
            model_name='depense',
            name='justificatif_url',
        ),
        migrations.AddField(
            model_name='depense',
            name='justificatif',
            field=models.ImageField(blank=True, null=True, upload_to='depenses/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(blank=True, help_text='Code-barres ou SKU.', max_length=50),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='devise',
            field=models.CharField(default='CFA', max_length=3),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='tva_default',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestion.article'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin Entreprise'), ('manager', 'Manager'), ('caissier', 'Caissier'), ('comptable', 'Comptable'), ('lecture_seule', 'Lecture Seule')], default='caissier', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('carte', 'Carte'), ('mobile_money', 'Mobile Money')], default='especes', max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('payee', 'Payée'), ('annulee', 'Annulée'), ('credit', 'Crédit')], default='payee', max_length=20),
        ),
    ]
