# Generated by Django 6.0 on 2025-12-23 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gestion', '0010_remove_client_gestion_cli_entrepr_03c662_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depense',
            name='justificatif',
        ),
        migrations.AddField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='depense',
            name='justificatif_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(blank=True, help_text='Code-barres ou référence SKU.', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='devise',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='tva_default',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='entreprise',
            field=models.ForeignKey(blank=True, help_text="L'entreprise à laquelle cet utilisateur est rattaché.", null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='gestion_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin Entreprise'), ('manager', 'Manager'), ('caissier', 'Caissier'), ('comptable', 'Comptable'), ('lecture_seule', 'Lecture Seule')], default='lecture_seule', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='gestion_user_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Especes'), ('carte', 'Carte'), ('mobile_money', 'Mobile_money')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('payee', 'Payee'), ('annulee', 'Annulee'), ('credit', 'Credit')], default='payee', max_length=20),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entreprise', 'nom'], name='gestion_cli_entrepr_03c662_idx'),
        ),
    ]
