# Generated by Django 6.0 on 2025-12-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_remove_depense_justificatif_article_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='stock_actuel',
        ),
    ]
