# Generated by Django 6.0 on 2025-12-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_remove_article_stock_actuel'),
    ]

    operations = [
        migrations.AddField(
            model_name='depense',
            name='fournisseur',
            field=models.CharField(blank=True, default='Inconnu', max_length=255, null=True),
        ),
    ]
