# Generated by Django 6.0 on 2026-01-30 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_depense_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=150)),
                ('telephone_client', models.CharField(blank=True, max_length=20)),
                ('bois', models.CharField(blank=True, help_text='Ex: Chêne, Rouge, etc.', max_length=100)),
                ('tissu', models.CharField(blank=True, help_text='Ex: Velours bleu, Cuir noir', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Détails supplémentaires sur le modèle')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_livraison_prevue', models.DateField()),
                ('total_commande', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acompte_verse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En fabrication'), ('pret', 'Prêt / Terminé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='en_attente', max_length=20)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
                ('vendeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
