# Generated by Django 6.0 on 2026-02-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='ville_client',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
