# Generated by Django 6.0 on 2026-02-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_commande_ville_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='telephone_client_libre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('devis', 'Devis'), ('en_attente', 'En attente'), ('en_cours', 'En fabrication'), ('pret', 'Prêt / Terminé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='devis', max_length=20),
        ),
    ]
