# Generated by Django 6.0 on 2026-06-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_user_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='code',
            field=models.CharField(blank=True, help_text='Code-barres ou référence SKU.', max_length=50, null=True),
        ),
    ]
