# Generated by Django 6.0 on 2026-06-18 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0018_alter_article_code_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='acompte',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Acompte versé pour les ventes à crédit.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='solde_credit',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant total dû par ce client.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='bois',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='commande',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='tissu',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='devise',
            field=models.CharField(default='CFA', max_length=3),
        ),
        migrations.AlterField(
            model_name='vente',
            name='mode_paiement',
            field=models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('banque', 'Virement bancaire'), ('carte', 'Carte bancaire')], default='especes', max_length=20),
        ),
        migrations.AlterField(
            model_name='vente',
            name='statut',
            field=models.CharField(choices=[('payee', 'Payée'), ('annulee', 'Annulée'), ('credit', 'À crédit')], default='payee', max_length=20),
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('solde_dette', models.DecimalField(decimal_places=2, default=0, help_text='Montant total dû à ce fournisseur.', max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
            ],
            options={
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='AchatFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(help_text="Nom libre si l'article n'est pas en stock.", max_length=200)),
                ('quantite', models.IntegerField(default=1)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_paye', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('banque', 'Virement bancaire'), ('carte', 'Carte bancaire')], default='especes', max_length=20)),
                ('statut_paiement', models.CharField(choices=[('non_paye', 'Non payé'), ('partiel', 'Partiellement payé'), ('paye', 'Payé')], default='non_paye', max_length=20)),
                ('date_achat', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_fournisseur', to='gestion.article')),
                ('declare_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.entreprise')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats', to='gestion.fournisseur')),
            ],
            options={
                'ordering': ['-date_achat'],
            },
        ),
        migrations.CreateModel(
            name='PaiementCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('especes', 'Espèces'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('moov_money', 'Moov Money'), ('banque', 'Virement bancaire'), ('carte', 'Carte bancaire')], default='especes', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements_credit', to='gestion.vente')),
            ],
            options={
                'ordering': ['-date_paiement'],
            },
        ),
    ]
