# Generated by Django 6.0 on 2026-06-18 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_add_fournisseur_achat_paiementcredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ouverture', 'Ouverture caisse'), ('depot', 'Dépôt / Alimentation'), ('retrait', 'Retrait'), ('ajustement', 'Ajustement')], default='depot', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_avant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_mouvement', models.DateField()),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_caisse', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_caisse', to='gestion.entreprise')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
