"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import dj_database_url
from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- SÉCURITÉ ---
# On récupère la clé depuis Render, sinon on utilise une clé par défaut pour le local
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-9vp*nc(e=nk^g4(jakyrz1_uephzyxfmtsm3w(jsb+0ce11gwv')

DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['backend-gestion-pme.onrender.com', 'localhost', '127.0.0.1']
CSRF_TRUSTED_ORIGINS = ['https://backend-gestion-pme.onrender.com']

# --- CONFIGURATION DRF (API) ---
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# --- APPLICATIONS ---
INSTALLED_APPS = [
    'cloudinary_storage',         # Doit être avant staticfiles
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'cloudinary',                 # <--- AJOUTÉ : Indispensable pour Cloudinary
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'gestion',                    # Ton application
]

# --- MIDDLEWARES ---
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # <--- AJOUTÉ : Pour les fichiers statiques sur Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', 
    'django.contrib.messages.middleware.MessageMiddleware',
    'gestion.middleware.TokenURLMiddleware', 
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
APPEND_SLASH = True

# --- BASE DE DONNÉES ---
DATABASES = {
    'default': dj_database_url.config(
        default='postgresql://postgres:Mims2408@localhost:5432/gestion_pme',
        conn_max_age=600
    )
}

# --- AUTHENTIFICATION ---
AUTH_USER_MODEL = 'gestion.User'

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# --- INTERNATIONALISATION ---
LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# --- FICHIERS STATIQUES ET MÉDIAS ---
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Configuration pour WhiteNoise (compression des fichiers statiques)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- CLOUDINARY (Stockage des logos) ---
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME', 'dfwgxjvyp'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY', '828715766475768'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET', 'IrnD-zoD_NGRWuJIZF_WRHiizKU'),
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# --- CORS ---
CORS_ALLOWED_ORIGINS = [
    "https://gestion-pme.netlify.app",
    "https://ma-gestion-pme.web.app",
    "http://localhost:3000",
    "http://127.0.0.1:8000",
]

# Ajoute ceci pour autoriser Flutter local (Chrome) quel que soit le port
CORS_ALLOW_ALL_ORIGINS = DEBUG  # En mode DEBUG, on accepte tout (pratique pour Flutter Web local)

# TRÈS IMPORTANT : Autorise les headers personnalisés
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]